[build]
  command = "cd frontend && npm run build"
  publish = "frontend/build"

[functions]
  directory = "backend/src"
  node_bundler = "esbuild"

[dev]
  targetPort = 3333
  port = 4444
  autoLaunch = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200