[build]
  command = "cd backend && npm ci && cp package.json package-lock.json src/ && cd ../frontend && npm ci && npm run build"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "backend/src"
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/functions"]

[dev]
  targetPort = 3333
  port = 4444
  autoLaunch = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200