[build]
  command = "cd backend && npm ci && cd ../frontend && npm ci && npm run build"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "backend/src"
  node_bundler = "esbuild"
  external_node_modules = [
    "@netlify/functions",
    "mongodb",
    "zod", 
    "jsonwebtoken",
    "bcryptjs"
  ]

[dev]
  targetPort = 3333
  port = 4444
  autoLaunch = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200